### ISSUE TITLE
Go from multi view to fullscreen black screen for second 

### ISSUE THREAD

**Issue by robbinonline** [NoahFetz/F1AppleTV#21]
Wow the multiview is awesome what a great job! When I checked your YouTube video how it’s works the only issue I have is going from a multiview to a full screen video the switch take 2 seconds with a black screen. That is not in your video. Any idea how to fix?

**Comment by NoahFetz** [comment]
It's the Apple TV adapting to the frame rate. In the next update this will happen when the first stream opens. If you don't want this (I recommend leaving this setting on to eliminate stuttering) you can go into your AppleTV settings under Video and audio and turn off adaptions

**Comment by robbinonline** [comment]
https://youtu.be/lR1eImWtM8I

**Comment by robbinonline** [comment]
Damm you faster then my YouTube url

**Comment by NoahFetz** [comment]
Yeah that's exactly that :)

**Comment by robbinonline** [comment]
I use the temp fix for tomorrow until the is a next update thanks. 

Btw do you think there is a option for the multiview to make the main channel bigger and the other channels a bit smaller.

**Comment by NoahFetz** [comment]
Oh I mean the black screen is still gonna be there, it's the Apple TV switching the frame rate. But this is not a bug, it's the same in Netflix for example or any other video you play with different frame rates.

And regarding the channel size: I tried it out when I started working on the player but it's difficult to get it to work right with the tiling, so that will need some time

**Comment by robbinonline** [comment]
My favorite view would be like this. Would be awesome if you can create like a setting where to select a premade layout or something and fill it with your own streams.

https://imgur.com/a/wzgv4vc

**Comment by NoahFetz** [comment]
Premade layouts are not a good idea since everyone has a different screen and aspect ratio

**Comment by robbinonline** [comment]
Not a idea to use percentages for ratio like 70%, 30% etc

**Comment by NoahFetz** [comment]
The problem is the following: The F1 feed is normally in 16:9 that means each player cell has to have a ratio of 16:9.
So you can only go with multiples of the smalest cell you have. With the current layout it's not that difficult. I take the square root of the number of players I have (let's say 24 that means sqrt is 4.89...) and I round that up to the nect whole number (in this case 5).
Now when I create a player cell I set it's width to 1/5th of the whole display's width and it's height to it's width/16*9 (to have it match it's content) that way it fills the whole screen.

Now if I want to make different sizes it gets way more complicated. Let's say you can make a player twoze the.
Now this one single player takes 4 of the smallest spots. That means in my height calculation I now have to take the number of players + (number of double sized players * 3 (because each takes 3 extra spots)) and take the square root of that. Not that difficult yet I had all that already at the beginning when I was experimenting with it...
Now comes the problem. The players are created from top left to bottom right.
Let's assume a 5 x 5 grid of players. I'm at line 2 on the last position and I get a double sized cell to make. But I can't make it since in this row there's only one spot left but it would take two, so I've got to shift it to the next row (which also leaves an ugly empty space in that case and we don't want that, do we?) now this cell takes position 1 and 2 on the 3rd row and position 1 and 2 on the fourth row and that means I may need another row since I left one spot open, so this invalidates all cells I made before so I've got to start again and make a 6x6 grid now this double sized cell gets to the 3rd last position on the 2nd row (assuming we keep the order) that now means I've got an extra row at the bottom because we don't have to shift it down. You see we're in an ininite loop like that. And it gets way more difficult if there are also for example cells that are four times the size and if there are multiple larger cells it gets even more difficult so they don't overlap etc.
As you can see I don't really have enough free time to get it right and I only do stuff if I do it right. So yeah I have it on the back of my head but it will take time..
