### ISSUE TITLE
Network timeouts cause stream to reset to the latest (live) moment in real time, when you're watching it delayed a few minutes.

### ISSUE THREAD

**Issue by alphex** [NoahFetz/F1AppleTV#29]
This morning I was late to sit down to watch the race, and when I started the Race, it was 5 or 6 laps in...

No problem... I hit "rewind", and started from the beginning.

Over the course of the 66 laps, at multiple times the feed stalled ... either my network, or the internet as a whole... who knows...

BUT, instead of pausing, and waiting to buffer, the stream jumped to the latest available time stamp (the live feed), and was stalled there as well.  

This forced me to pause, and rewind again, back to where ever I was in the race...

Feature Request / Bug Fix:
When the network stalls out, make sure the feed doesn't reset to the LIVE time stamp (jump to realtime), if a person is watching the race delayed, WHILE its going on.

This has never happened in the past, because usually I'm watching the race later in the day, well after its over.

Thank you for a fantastic app!

**Comment by NoahFetz** [comment]
The player assumes you want to watch it live so it does that by itself. That's a behavior that Apple put there intentionally (I think). Apple's player api is locked down pretty well. I could actually get the info I need and reset to this point, but it's not straight forward at all and would probably cause other bugs since like I said I would have to overwrite a default behavior.
I'll close this for now since I haven't experienced any buffering for the last few months and since this is a edge case there are suggestions that would benefit more users.
