### ISSUE TITLE
New Apple TV remote does not work well with the swipe gesture to open the channel menu

### ISSUE THREAD

**Issue by grunka** [NoahFetz/F1AppleTV#33]
Due to the smaller swipe-sensitive area and a bigger focus on actual buttons on the [new remote](https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/MJFM3?wid=1144&hei=1144&fmt=jpeg&qlt=80&.v=1617222660000) most attempts to move left in a multi camera view using swiping opens the channel menu.

Also, the swiping is a configurable option for this new remote allowing you to turn it off for accessibility reasons (or if you just get a bit too annoyed at buttons that can change what you've selected while clicking them). With it off I find no way of activating the channel menu.

My most accessible suggestion would be to add a button on the player controls that opens the same list.

**Comment by NoahFetz** [comment]
And what does the app do when you just click to the left/right/up etc? I don't have the new remote and I don't plan on buying it since I like the big touchpad of the "old" one.
I'm a bit confused now, since I got someone's feedback, that it's much better with the new remote.

I'll see if I can fetch in the code what remote it is and then add the button if it's the new one

**Comment by grunka** [comment]
When playing a single channel none of the directions does anything. The middle button opens up the little menu with the play controls. Closing the last channel and clicking the middle button opens the channel selector and you can add channels.

When multiple feeds are playing the directions move around the selection showing the channel name as expected.

**Comment by robbinonline** [comment]
Everything works fine here with the new controller.

**Comment by jreese** [comment]
I would also really appreciate having a button/icon to open the channel selection rather than depending on a swipe gesture. I mostly use a Logitech Harmony remote or Xbox controller to control the Apple TV, both of which only support directional/dpad inputs. Even when not using that, I vastly prefer to have swiping gestures disabled, because that makes the remote much more predictable to use, with far fewer accidental inputs.

Otherwise, I enjoy the app, and thank you so much for your time and effort working on it!
