### ISSUE TITLE
Missing audio tracks

### ISSUE THREAD

**Issue by joel931767** [NoahFetz/F1AppleTV#49]
First of all, thank you Noah! The app is a great improvement for my F1 watching habits!

But since today I’m missing the different audio tracks. Instead of the different languages it says “unknown” and is just giving me English as default.

**Comment by NoahFetz** [comment]
tvOS has the same issue as the official iOS App since it's a problem with the way Apple changed something in the iOS/tvOS 15 updates. I had to apply a workaround or you wouldn't be able to play anything at all and just see a black screen. If you go to the settings tab in my app select the language you want there. You won't be able to change the audio while playing until this issue is resolved by Apple (Or F1TV if they find anything to fix this)

**Comment by joel931767** [comment]
Thanks! That’s a good workaround!
