### ISSUE TITLE
Samsung Tizen Smart Hub support?

### ISSUE THREAD

**Issue by dahfuzion1** [NoahFetz/F1AppleTV#5]
Hi there,

Any chance you could / intend to create an app to support Samsung Smart TV's? (Tizen app store)

Based on the released info this isn't being considered for an app in the near future, so would be bound to chromecast..

Thanks in advance for your return.

Best regards

**Comment by NoahFetz** [comment]
Sorry to disappoint you, but that will never happen because of these reasons:

1. I don't have a Samsung TV so I firstly can't test it and secondly that means I don't need an app on there for myself (I did this app here because I use it myself, otherwise I would've never made it)
2. From what I know about this platform it's the same as with Android. There are millions of different device configurations and it's a constant bug fest which I'm not going to get myself into
3. I don't have any experience coding on this platform
4. No spare time for that

I still wish you a nice day and thanks for the question
- Noah
