### ISSUE TITLE
Livestream testing days not loading

### ISSUE THREAD

**Issue by LiroyvH** [NoahFetz/F1AppleTV#63]
Hi,

Just wanted to let you know that live playback of the testing days in Bahrain doesn't seem to be working. I've built the app manually (did that ever since TF expired) to an Apple TV (4th generation) with a developer account. Playback of material from the archive, including session 1 from the testing days, works fine and some recaps such as the "the story of the 2022 season" stuff works splendid!

But the livestream of testing days just gives a black screen with a playback bar that never starts running. I tried to open the stream on my iPad: loads instantly there in the official F1 TV app. Just won't load in VroomTV.

I'm not sure if it's relevant, but I did see this scrolling by multiple times when starting the livestream:
`2023-02-23 13:45:52.022879+0100 F1A-TV[18747:3027191] [NowPlaying] [MRPlaybackQueueServiceClient] playbackQueueRequest [REDACTED] PineBoard-34 [REDACTED] responded to asset request with error Error Domain=kMRMediaRemoteFrameworkErrorDomain Code=15 "Operation requires a client data source to have been registered." UserInfo={NSLocalizedDescription=Operation requires a client data source to have been registered.}`
However, Google'ing that I'm not sure if it is relevant - could be, could not be.

I am logged in with a valid account with active subscription.
I tried logging out and back in (note: turns out this doesn't register as logged out in F1TV, so got weird errors until I realised I must've hit my device limit; had to manually log out the VroomTV instance in my account :P), didn't solve the problem.

Is this a problem with self-built app or a generic issue with the current API?

**Comment by NoahFetz** [comment]
I don't have access to an AppleTV right now, I'll test it later at home

**Comment by Oekie74** [comment]
Hi I just wanna say i have the same issue here. Only the livestream. 
Keep up the good work Noah !

Greetings Oekie

**Comment by NoahFetz** [comment]
Should work again with the fix

**Comment by Oekie74** [comment]
Tnx Noah 👊🏼Met vriendelijke groet,Roy KampsOp 25.02.2023 om 16:04 heeft Noah Fetz ***@***.***> het volgende geschreven:﻿
Should work again with the fix

**Comment by LiroyvH** [comment]
@NoahFetz Thanks! Will rebuild and check it out this weekend during FP1! Will let you know if it fixed it. :)

**Comment by ContagiousAmbition** [comment]
Not sure if it's related @NoahFetz but I'm having an issue trying to stream F2 Practice and I get:

`Response serialization failed:
Response could not be decoded because of error:
The data couldn't be read because it is missing 
Failure Reason: decodingFailed(error: Swift. DecodingError.keyNotFound(CodingKeys (stringValue:"entitlement Token", intValue: nil), Swift.DecodingError.Context(codingPa th: [CodingKeys(string Value:"resultObj", intValue: nil)].debugDescription: "No value associated with key CodingKeys (string Value:(\"entitlement Token\", intValue: nil) ("\entitlement Token\").".underlying Error: nil)))`

Apologies if anything here is slightly off; I had to use iOS copy/paste from a photo as the error doesn't stay on screen too long.

The same credentials got the stream running on my laptop via a VPN. AFAIK I can't get a VPN on Apple TV, hence using your app.

**Comment by NoahFetz** [comment]
You can't get around being in an unsupported region without a VPN. That's why there's no authorization for the stream

**Comment by ContagiousAmbition** [comment]
@NoahFetz thanks for the quick reply. Is this a new development? I (believe I) used to use the app for this reason when I was in another country with rights differences.

**Comment by NoahFetz** [comment]
I don't know, I think it used to be like that all the time but maybe there are some changes this year 🤷‍♂️

**Comment by LiroyvH** [comment]
@NoahFetz 
Just tested it with FP1 Bahrain - can confirm it works now, thank you very much. :)

**Comment by Oekie74** [comment]
Hi Noah,Live tv works but turns on screensaver after a while… Is this something in your app, because I’m not recon this issue in other apps? Best Regards Roy KampsOp 03.03.2023 om 13:04 heeft Liroy van Hoewijk ***@***.***> het volgende geschreven:﻿
@NoahFetz
Just tested it with FP1 Bahrain - can confirm it works now, thank you very much. :)
